### ISSUE TITLE
Deprecation warnings for node 12

### ISSUE THREAD

**Issue by kevinpapst** [mvasigh/dispatch-action#29]
Hi @mvasigh,

thanks for your work!

Using your action I get a warning nowadays in every run:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: mvasigh/dispatch-action@1.1.6
```

An example run is here: https://github.com/kevinpapst/kimai2/actions/runs/3541080089

I guess that is related to this line:
https://github.com/mvasigh/dispatch-action/blob/main/action.yml#L26

Do you still maintain this action?

**Comment by mvasigh** [comment]
Hi @kevinpapst, thank you for the heads up!

I no longer actively maintain this action. I think these days there are likely other options on the marketplace that perform the same function (sending repository dispatch events), I'd recommend trying out one of those.

**Comment by mvasigh** [comment]
If useful, [this action](https://github.com/marketplace/actions/repository-dispatch) seems like a good actively maintained alternative.

**Comment by kevinpapst** [comment]
Yep 👍 Seems the workflow diff is very small as well. From:

```
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@1.1.6
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repo: target
          owner: username
          event_type: my_event
```

to 

```
    steps:
      - name: Emit repository_dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: username/target
          event_type: my_event
```

Thanks for your action, which I used for quite a while. 

You can close the issue if you like or keep it open for the next user 😄
